language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2
sudo: false
cache: bundler
script:
  - "bundle exec rake $TASK"
env:
  - TASK=spec
  - TASK=rails:spec
  - TASK=bench TIME=10
matrix:
  allow_failures:
    - env: TASK=bench TIME=10
  exclude:
    - rvm: 2.0.0
      env: TASK=bench TIME=10
    - rvm: 2.0.0
      env: TASK=rails:spec
    - rvm: 2.1
      env: TASK=bench TIME=10
    - rvm: 2.1
      env: TASK=rails:spec
